language: python
python:
- '3.6'
install:
- pip install -e .
script:
- pytest -v --cov-report term --cov=gym_adserver/envs
after_success:
- codecov
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "PweZMSjp5wwvdSYuZhmxO0HdIEr9rAPqP/aywuaNdK0NJTLezYHUbQffNS7DNflhdEHlRs4qCWXjc/BD9JP6B5FUS6iRFBWIXBUo/Ypc/BKI6BDBFIg9I1l8WdyibDqxPRMKYdB5kUUmtDYDj1bcXSeD3owdhdbKBNrMsjWFuZcWwqGtZkQ7T81dCo0D12b36t46pAfluZslGKbWc10yjCk2ET3lU4Hoz9rb3w0c19N+C2RT+4Za8TMIbKaromGcwJt0dOjF3jTNBkplTwxGkPW8EXCsNgzLZkc+gwPQ4cW2Y4Fy9O0LTfX8BbnOZwK+D/YBiyHb4eqRYNKQQP+0ZrTRH8EmbcZMjxFqigDQWjUkKoUZMri0kJp5LUcSpkulIRYu9n+P7ALbXY4S7X2T5iSvabO3bezHKh48Oa2S8lJMLc/5N28jTShM86AK/C3G7Jbqq99mm16f/vQruENR3cebslY0XYHNjtz4GDJye9VwuIv8yZp4PII7ILaQvMhKpVNF4zs/vECPBXXX3XMOG0RWasRf8AqhIKD4ZzE7gn1wkfb343JoAqo5ezTi8QGGrrfZXT34a+4Q+7/unc614Jmn4I+brwr//ZR04h4Yy2uwdLqe0p2DXLweNuuoah+vpvSZxRmQyhdnwlQtXlQ4hOUcR/0NoUrEROGOCNIkpM8="
  on:
    tags: true
    branch: master
    distributions: sdist bdist_wheel
    repo: falox/gym-adserver
  skip_cleanup: 'true'
